# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0002_business_post_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='ambulance',
            field=models.CharField(blank=True, default='911', max_length=12),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='image',
            field=models.ImageField(null=True, upload_to='neighborhood_photos'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(blank=True, default='Somewhere in Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police',
            field=models.CharField(blank=True, default='911', max_length=12),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='population',
            field=models.CharField(blank=True, default='Unknown', max_length=128),
        ),
    ]
