# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbor', '0003_auto_20180528_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='additional_details',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, upload_to='business_images'),
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='neighbor.Neighborhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='idnumber',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_dps'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='neighbor.Neighborhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
