# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbor', '0004_auto_20180528_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighbor.Neighborhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_post',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
