# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0005_auto_20180528_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
    ]
