# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0012_auto_20180529_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='image',
            field=models.ImageField(null=True, upload_to='neighborhood_photos/'),
        ),
    ]
