# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0013_auto_20180529_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbor.Neighborhood'),
        ),
    ]
