# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0014_auto_20180530_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='neighbor.Neighborhood'),
            preserve_default=False,
        ),
    ]
